spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifetime: 580000
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD}
  jpa:
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
    open-in-view: false

auth:
  jwt:
    secretKey: ${JWT_SECRET_KEY:Knock}
    accessExp: ${JWT_ACCESS_EXP:3600}
    refreshExp: ${JWT_REFRESH_EXP:3600}
    header: ${JWT_HEADER:Authorization}
    prefix: ${JWT_PREFIX:Bearer}
